// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: protobuf_entity/feed.proto

package protobuf_entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedId         string `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	FeedUrl        string `protobuf:"bytes,2,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	SiteUrl        string `protobuf:"bytes,3,opt,name=site_url,json=siteUrl,proto3" json:"site_url,omitempty"`
	Title          string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Language       string `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	IconContent    string `protobuf:"bytes,7,opt,name=icon_content,json=iconContent,proto3" json:"icon_content,omitempty"`
	Status         int32  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Reading        int64  `protobuf:"varint,9,opt,name=reading,proto3" json:"reading,omitempty"`
	Likes          int64  `protobuf:"varint,10,opt,name=likes,proto3" json:"likes,omitempty"`
	Followers      int64  `protobuf:"varint,11,opt,name=followers,proto3" json:"followers,omitempty"`
	LastModifyTime int64  `protobuf:"varint,12,opt,name=last_modify_time,json=lastModifyTime,proto3" json:"last_modify_time,omitempty"`
	IconType       string `protobuf:"bytes,13,opt,name=icon_type,json=iconType,proto3" json:"icon_type,omitempty"`
}

func (x *Feed) Reset() {
	*x = Feed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_feed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_feed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_feed_proto_rawDescGZIP(), []int{0}
}

func (x *Feed) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *Feed) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *Feed) GetSiteUrl() string {
	if x != nil {
		return x.SiteUrl
	}
	return ""
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feed) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Feed) GetIconContent() string {
	if x != nil {
		return x.IconContent
	}
	return ""
}

func (x *Feed) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Feed) GetReading() int64 {
	if x != nil {
		return x.Reading
	}
	return 0
}

func (x *Feed) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Feed) GetFollowers() int64 {
	if x != nil {
		return x.Followers
	}
	return 0
}

func (x *Feed) GetLastModifyTime() int64 {
	if x != nil {
		return x.LastModifyTime
	}
	return 0
}

func (x *Feed) GetIconType() string {
	if x != nil {
		return x.IconType
	}
	return ""
}

type ListFeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feeds []*Feed `protobuf:"bytes,1,rep,name=feeds,proto3" json:"feeds,omitempty"`
}

func (x *ListFeed) Reset() {
	*x = ListFeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_feed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeed) ProtoMessage() {}

func (x *ListFeed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_feed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeed.ProtoReflect.Descriptor instead.
func (*ListFeed) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_feed_proto_rawDescGZIP(), []int{1}
}

func (x *ListFeed) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

type FeedNameOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Time   int64  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Data   string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FeedNameOperation) Reset() {
	*x = FeedNameOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_feed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedNameOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedNameOperation) ProtoMessage() {}

func (x *FeedNameOperation) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_feed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedNameOperation.ProtoReflect.Descriptor instead.
func (*FeedNameOperation) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_feed_proto_rawDescGZIP(), []int{2}
}

func (x *FeedNameOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedNameOperation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FeedNameOperation) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *FeedNameOperation) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type FeedOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Time   int64  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Data   string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	FeedId string `protobuf:"bytes,5,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
}

func (x *FeedOperation) Reset() {
	*x = FeedOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_feed_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedOperation) ProtoMessage() {}

func (x *FeedOperation) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_feed_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedOperation.ProtoReflect.Descriptor instead.
func (*FeedOperation) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_feed_proto_rawDescGZIP(), []int{3}
}

func (x *FeedOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedOperation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FeedOperation) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *FeedOperation) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *FeedOperation) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

type FeedIncremntPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider           string               `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	FeedName           string               `protobuf:"bytes,2,opt,name=feed_name,json=feedName,proto3" json:"feed_name,omitempty"`
	FromTime           int64                `protobuf:"varint,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	EndTime            int64                `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Interval           int64                `protobuf:"varint,5,opt,name=interval,proto3" json:"interval,omitempty"`
	FeedOperations     []*FeedOperation     `protobuf:"bytes,6,rep,name=feed_operations,json=feedOperations,proto3" json:"feed_operations,omitempty"`
	FeedNameOperations []*FeedNameOperation `protobuf:"bytes,7,rep,name=feed_name_operations,json=feedNameOperations,proto3" json:"feed_name_operations,omitempty"`
}

func (x *FeedIncremntPackage) Reset() {
	*x = FeedIncremntPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_feed_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedIncremntPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedIncremntPackage) ProtoMessage() {}

func (x *FeedIncremntPackage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_feed_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedIncremntPackage.ProtoReflect.Descriptor instead.
func (*FeedIncremntPackage) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_feed_proto_rawDescGZIP(), []int{4}
}

func (x *FeedIncremntPackage) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FeedIncremntPackage) GetFeedName() string {
	if x != nil {
		return x.FeedName
	}
	return ""
}

func (x *FeedIncremntPackage) GetFromTime() int64 {
	if x != nil {
		return x.FromTime
	}
	return 0
}

func (x *FeedIncremntPackage) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FeedIncremntPackage) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *FeedIncremntPackage) GetFeedOperations() []*FeedOperation {
	if x != nil {
		return x.FeedOperations
	}
	return nil
}

func (x *FeedIncremntPackage) GetFeedNameOperations() []*FeedNameOperation {
	if x != nil {
		return x.FeedNameOperations
	}
	return nil
}

type FeedAllPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider string  `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	FeedName string  `protobuf:"bytes,2,opt,name=feed_name,json=feedName,proto3" json:"feed_name,omitempty"`
	Feeds    []*Feed `protobuf:"bytes,3,rep,name=feeds,proto3" json:"feeds,omitempty"`
}

func (x *FeedAllPackage) Reset() {
	*x = FeedAllPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_feed_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedAllPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedAllPackage) ProtoMessage() {}

func (x *FeedAllPackage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_feed_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedAllPackage.ProtoReflect.Descriptor instead.
func (*FeedAllPackage) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_feed_proto_rawDescGZIP(), []int{5}
}

func (x *FeedAllPackage) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FeedAllPackage) GetFeedName() string {
	if x != nil {
		return x.FeedName
	}
	return ""
}

func (x *FeedAllPackage) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

var File_protobuf_entity_feed_proto protoreflect.FileDescriptor

var file_protobuf_entity_feed_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xf9, 0x02,
	0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x66, 0x65, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69,
	0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69,
	0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x63, 0x6f,
	0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6b, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x63, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x65, 0x65, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x65, 0x65, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x05, 0x66, 0x65, 0x65,
	0x64, 0x73, 0x22, 0x63, 0x0a, 0x11, 0x46, 0x65, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x78, 0x0a, 0x0d, 0x46, 0x65, 0x65, 0x64, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x65, 0x65, 0x64, 0x49,
	0x64, 0x22, 0xc1, 0x02, 0x0a, 0x13, 0x46, 0x65, 0x65, 0x64, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d,
	0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x47, 0x0a, 0x0f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0e, 0x66, 0x65, 0x65, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x54, 0x0a, 0x14, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x46, 0x65, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x12, 0x66, 0x65, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x76, 0x0a, 0x0e, 0x46, 0x65, 0x65, 0x64, 0x41, 0x6c, 0x6c,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2b, 0x0a, 0x05, 0x66, 0x65, 0x65, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x05, 0x66, 0x65, 0x65, 0x64, 0x73, 0x42, 0x12, 0x5a,
	0x10, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_entity_feed_proto_rawDescOnce sync.Once
	file_protobuf_entity_feed_proto_rawDescData = file_protobuf_entity_feed_proto_rawDesc
)

func file_protobuf_entity_feed_proto_rawDescGZIP() []byte {
	file_protobuf_entity_feed_proto_rawDescOnce.Do(func() {
		file_protobuf_entity_feed_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_entity_feed_proto_rawDescData)
	})
	return file_protobuf_entity_feed_proto_rawDescData
}

var file_protobuf_entity_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_entity_feed_proto_goTypes = []interface{}{
	(*Feed)(nil),                // 0: protobuf_entity.Feed
	(*ListFeed)(nil),            // 1: protobuf_entity.ListFeed
	(*FeedNameOperation)(nil),   // 2: protobuf_entity.FeedNameOperation
	(*FeedOperation)(nil),       // 3: protobuf_entity.FeedOperation
	(*FeedIncremntPackage)(nil), // 4: protobuf_entity.FeedIncremntPackage
	(*FeedAllPackage)(nil),      // 5: protobuf_entity.FeedAllPackage
}
var file_protobuf_entity_feed_proto_depIdxs = []int32{
	0, // 0: protobuf_entity.ListFeed.feeds:type_name -> protobuf_entity.Feed
	3, // 1: protobuf_entity.FeedIncremntPackage.feed_operations:type_name -> protobuf_entity.FeedOperation
	2, // 2: protobuf_entity.FeedIncremntPackage.feed_name_operations:type_name -> protobuf_entity.FeedNameOperation
	0, // 3: protobuf_entity.FeedAllPackage.feeds:type_name -> protobuf_entity.Feed
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_entity_feed_proto_init() }
func file_protobuf_entity_feed_proto_init() {
	if File_protobuf_entity_feed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_entity_feed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_entity_feed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_entity_feed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedNameOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_entity_feed_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_entity_feed_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedIncremntPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_entity_feed_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedAllPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_entity_feed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_entity_feed_proto_goTypes,
		DependencyIndexes: file_protobuf_entity_feed_proto_depIdxs,
		MessageInfos:      file_protobuf_entity_feed_proto_msgTypes,
	}.Build()
	File_protobuf_entity_feed_proto = out.File
	file_protobuf_entity_feed_proto_rawDesc = nil
	file_protobuf_entity_feed_proto_goTypes = nil
	file_protobuf_entity_feed_proto_depIdxs = nil
}
