// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: protobuf_entity/discoveryfeed.proto

package protobuf_entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryFeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedUrl     string `protobuf:"bytes,1,opt,name=feed_url,json=feedUrl,proto3" json:"feed_url,omitempty"`
	SiteUrl     string `protobuf:"bytes,2,opt,name=site_url,json=siteUrl,proto3" json:"site_url,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IconType    string `protobuf:"bytes,5,opt,name=icon_type,json=iconType,proto3" json:"icon_type,omitempty"`
	IconContent string `protobuf:"bytes,6,opt,name=icon_content,json=iconContent,proto3" json:"icon_content,omitempty"`
}

func (x *DiscoveryFeed) Reset() {
	*x = DiscoveryFeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_discoveryfeed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryFeed) ProtoMessage() {}

func (x *DiscoveryFeed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_discoveryfeed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryFeed.ProtoReflect.Descriptor instead.
func (*DiscoveryFeed) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_discoveryfeed_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryFeed) GetFeedUrl() string {
	if x != nil {
		return x.FeedUrl
	}
	return ""
}

func (x *DiscoveryFeed) GetSiteUrl() string {
	if x != nil {
		return x.SiteUrl
	}
	return ""
}

func (x *DiscoveryFeed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiscoveryFeed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiscoveryFeed) GetIconType() string {
	if x != nil {
		return x.IconType
	}
	return ""
}

func (x *DiscoveryFeed) GetIconContent() string {
	if x != nil {
		return x.IconContent
	}
	return ""
}

type ListDiscoveryFeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiscoveryFeeds []*DiscoveryFeed `protobuf:"bytes,1,rep,name=discoveryFeeds,proto3" json:"discoveryFeeds,omitempty"`
}

func (x *ListDiscoveryFeed) Reset() {
	*x = ListDiscoveryFeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_entity_discoveryfeed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDiscoveryFeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiscoveryFeed) ProtoMessage() {}

func (x *ListDiscoveryFeed) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_discoveryfeed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiscoveryFeed.ProtoReflect.Descriptor instead.
func (*ListDiscoveryFeed) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_discoveryfeed_proto_rawDescGZIP(), []int{1}
}

func (x *ListDiscoveryFeed) GetDiscoveryFeeds() []*DiscoveryFeed {
	if x != nil {
		return x.DiscoveryFeeds
	}
	return nil
}

var File_protobuf_entity_discoveryfeed_proto protoreflect.FileDescriptor

var file_protobuf_entity_discoveryfeed_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x66, 0x65, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0xbd, 0x01, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65, 0x65, 0x64,
	0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x63, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x5b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65, 0x64, 0x12, 0x46, 0x0a, 0x0e, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65, 0x65, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x46,
	0x65, 0x65, 0x64, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x46, 0x65,
	0x65, 0x64, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_entity_discoveryfeed_proto_rawDescOnce sync.Once
	file_protobuf_entity_discoveryfeed_proto_rawDescData = file_protobuf_entity_discoveryfeed_proto_rawDesc
)

func file_protobuf_entity_discoveryfeed_proto_rawDescGZIP() []byte {
	file_protobuf_entity_discoveryfeed_proto_rawDescOnce.Do(func() {
		file_protobuf_entity_discoveryfeed_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_entity_discoveryfeed_proto_rawDescData)
	})
	return file_protobuf_entity_discoveryfeed_proto_rawDescData
}

var file_protobuf_entity_discoveryfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_entity_discoveryfeed_proto_goTypes = []interface{}{
	(*DiscoveryFeed)(nil),     // 0: protobuf_entity.DiscoveryFeed
	(*ListDiscoveryFeed)(nil), // 1: protobuf_entity.ListDiscoveryFeed
}
var file_protobuf_entity_discoveryfeed_proto_depIdxs = []int32{
	0, // 0: protobuf_entity.ListDiscoveryFeed.discoveryFeeds:type_name -> protobuf_entity.DiscoveryFeed
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_entity_discoveryfeed_proto_init() }
func file_protobuf_entity_discoveryfeed_proto_init() {
	if File_protobuf_entity_discoveryfeed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_entity_discoveryfeed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryFeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_entity_discoveryfeed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDiscoveryFeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_entity_discoveryfeed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_entity_discoveryfeed_proto_goTypes,
		DependencyIndexes: file_protobuf_entity_discoveryfeed_proto_depIdxs,
		MessageInfos:      file_protobuf_entity_discoveryfeed_proto_msgTypes,
	}.Build()
	File_protobuf_entity_discoveryfeed_proto = out.File
	file_protobuf_entity_discoveryfeed_proto_rawDesc = nil
	file_protobuf_entity_discoveryfeed_proto_goTypes = nil
	file_protobuf_entity_discoveryfeed_proto_depIdxs = nil
}
